// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADq54iDSthSItQ1ZfmsACvCuq3C-4BsqY',
    appId: '1:62638395135:web:31e64662b1c5854b1f46ca',
    messagingSenderId: '62638395135',
    projectId: 'gradhub-feb6e',
    authDomain: 'gradhub-feb6e.firebaseapp.com',
    storageBucket: 'gradhub-feb6e.appspot.com',
    measurementId: 'G-GGR07299FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BH2H42i7aOMK3Waaixx4hacVn5QRV9E',
    appId: '1:62638395135:android:46d9ac0729f1e7e31f46ca',
    messagingSenderId: '62638395135',
    projectId: 'gradhub-feb6e',
    storageBucket: 'gradhub-feb6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJZWxeoT9N_c84C0UHOyzKSsXfaLrq64',
    appId: '1:62638395135:ios:95ffdc32fcde419f1f46ca',
    messagingSenderId: '62638395135',
    projectId: 'gradhub-feb6e',
    storageBucket: 'gradhub-feb6e.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJZWxeoT9N_c84C0UHOyzKSsXfaLrq64',
    appId: '1:62638395135:ios:95ffdc32fcde419f1f46ca',
    messagingSenderId: '62638395135',
    projectId: 'gradhub-feb6e',
    storageBucket: 'gradhub-feb6e.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADq54iDSthSItQ1ZfmsACvCuq3C-4BsqY',
    appId: '1:62638395135:web:1fc64069ea54959b1f46ca',
    messagingSenderId: '62638395135',
    projectId: 'gradhub-feb6e',
    authDomain: 'gradhub-feb6e.firebaseapp.com',
    storageBucket: 'gradhub-feb6e.appspot.com',
    measurementId: 'G-HCHYE8BZ05',
  );
}
